# Generated by Django 2.2.28 on 2024-02-04 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rango', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgeory',
            new_name='Category',
        ),
    ]
